### ISSUE TITLE
[Bug] incorrect display in system night (dark) mode

### ISSUE THREAD

**Issue by Ayagikei** [Ayagikei/calendar-account-manager#1]
![Screenshot_20211108-233318](https://user-images.githubusercontent.com/29143057/140770977-ac2c749e-1a6f-45ed-bd19-d15715d32703.jpg)

**Comment by somilror200** [comment]
Can you explain a bit more what is the issue?

**Comment by Ayagikei** [comment]
> Can you explain a bit more what is the issue?

Sorry for the confusion.

When the system turns on the global night mode, the text in the app is changed to white by default (the same color as the background), so the text is no longer visible.
At the same time, some icon backgrounds (like the delete icon button) are not properly adapted to the night mode.

Maybe we should follow the MD3 guide to adapt to night mode.

**Comment by somilror200** [comment]
I can't find an activity_main.xml file in your project

**Comment by Ayagikei** [comment]
> I can't find an activity_main.xml file in your project

Its UI is based on the [Jetpack Compose](https://developer.android.com/jetpack/compose) instead of the standard android view UI.

**Comment by somilror200** [comment]
I have created a pull request after solving these two problems, the text color and the delete button color

**Comment by Ayagikei** [comment]
> I have created a pull request after solving these two problems, the text color and the delete button color

Get it. Thanks for your work!

**Comment by somilror200** [comment]
I need to contact you but was not able to find our email address, please can you drop it here? (I will delete the comment once I get your email)

**Comment by Ayagikei** [comment]
***@***.***



来自 16s Pro

-------- 原始邮件 --------
发件人：Somil Garak ***@***.***>
时间：2021年11月15日 23:55
收件人：Ayagikei/calendar-account-manager ***@***.***>
抄送：AyagiKei ***@***.***>,State change ***@***.***>
主题：Re: [Ayagikei/calendar-account-manager] [Bug] incorrect display in system night (dark) mode (Issue #1)

**Comment by somilror200** [comment]
can you email me on somilror200@gmail.com or [wa.me/918708078902](Whatsapp link)
Your email address is displayed as ****@***.*** here

**Comment by somilror200** [comment]
Can you send me a mail on somilror200@gmail.com
Your email address is displayed as ****@***.***

**Comment by Ayagikei** [comment]
> somilror200@gmail.com

Sent.
